### ISSUE TITLE
Can we get a version for Mac?

### ISSUE THREAD

**Issue by ConnorBarthet** [hunter-meloche/siri-gpt#2]
Something that takes text input and maybe saves the log in a text file rather than the notes app.

**Comment by hunter-meloche** [comment]
Hey @ConnorBarthet I can look into that. I know macOS has Siri, so it may be possible.

**Comment by hunter-meloche** [comment]
@ConnorBarthet I just realized that all of this automatically works on macOS because Apple added Shortcuts in Monterey. Making a version that just creates text files is possible. Ideally, how would you want it set up? I can easily have it create a new text file named after the initial prompt for each conversation.
